sonata_admin:
    title: 'Karma Shop'
    title_logo: assets/img/fav.png
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    options:
        legacy_twig_text_extension: false
    templates:
        # Override default template
        layout: Admin/standard_layout.html.twig
    assets:
        extra_stylesheets:
            - assets/css/sonata-admin-overwrite.css # your css-file to add

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
