admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /admin/media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /admin/media

controllers_api:
    resource: '../../src/Controller/Api/'
    type: annotation
    prefix: '/api'
    name_prefix: 'api_'

kernel:
    resource: ../../src/Kernel.php
    type: annotation
