version: "3.1"
services:
  mysql:
    image: mysql:8.0
    container_name: karma-shop-mysql-v2
    volumes:
      - ./karma-shop.sql:/docker-entrypoint-initdb.d/karma-shop.sql
    command: ['--default-authentication-plugin=mysql_native_password']
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=karma-shop
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=mysql
    restart: always
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: karma-shop-phpmyadmin-v2
    restart: always
    links:
      - mysql:db
    ports:
      - "8601:80"
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=mysql
      - PMA_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: karma-shop-nginx-v2
    volumes:
      - ./..:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/000-default.conf
    ports:
      - "8600:8600"
    restart: always
    links:
      - php
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: karma-shop-php-v2
    restart: always
    links:
      - mysql
    networks:
      - app-network
    volumes:
      - ./..:/var/www/html
      - './php/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'

networks:
  app-network:
    driver: bridge
