services:
  admin.shop.brand:
    class: App\Admin\ShopBrandAdmin
    arguments: [~, App\Entity\ShopBrand, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Shop, label: Brand, icon: "<i class=\"fa fa-shopping-cart\"></i>" }

  admin.shop.category:
    class: App\Admin\ShopCategoryAdmin
    arguments: [~, App\Entity\ShopCategory, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Shop, label: Category }

  admin.shop.color:
    class: App\Admin\ShopColorAdmin
    arguments: [~, App\Entity\ShopColor, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Shop, label: Color }

  admin.shop.product_review:
    class: App\Admin\ProductReviewAdmin
    arguments: [~, App\Entity\ProductReview, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Shop, label: Product review }

  admin.shop.contact:
    class: App\Admin\ContactAdmin
    arguments: [~, App\Entity\Contact, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Site, label: Contact, icon: "<i class=\"fa fa-cogs\"></i>" }

  admin.shop.newsletter:
    class: App\Admin\NewsletterAdmin
    arguments: [~, App\Entity\Newsletter, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Site, label: Newsletter }

  admin.admin_user:
    class: App\Admin\AdminUserAdmin
    arguments: [~, App\Entity\AdminUser, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Users, label: Admin users, icon: "<i class=\"fa fa-users\"></i>" }
