services:
  admin.shop.brand:
    class: App\Admin\ShopBrandAdmin
    arguments: [~, App\Entity\ShopBrand, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Shop, label: Brand, icon: "<i class=\"fa fa-shopping-cart\"></i>" }

  admin.shop.category:
    class: App\Admin\ShopCategoryAdmin
    arguments: [~, App\Entity\ShopCategory, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Shop, label: Category }

  admin.shop.color:
    class: App\Admin\ShopColorAdmin
    arguments: [~, App\Entity\ShopColor, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Shop, label: Color }

  admin.shop.product_review:
    class: App\Admin\ProductReviewAdmin
    arguments: [~, App\Entity\ProductReview, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Shop, label: Product review }

  admin.blog.post:
    class: App\Admin\BlogPostAdmin
    arguments: [~, App\Entity\BlogPost, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Blog, label: Post, icon: "<i class=\"fa fa-pencil\"></i>" }

  admin.blog.tag:
    class: App\Admin\BlogTagAdmin
    arguments: [ ~, App\Entity\BlogTag, ~ ]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Blog, label: Tag }

  admin.blog.category:
    class: App\Admin\BlogCategoryAdmin
    arguments: [ ~, App\Entity\BlogCategory, ~ ]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Blog, label: Category }

  admin.shop.contact:
    class: App\Admin\ContactAdmin
    arguments: [~, App\Entity\Contact, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Site, label: Contact, icon: "<i class=\"fa fa-cogs\"></i>" }

  admin.shop.newsletter:
    class: App\Admin\NewsletterAdmin
    arguments: [~, App\Entity\Newsletter, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Site, label: Newsletter }

  admin.admin_user:
    class: App\Admin\AdminUserAdmin
    arguments: [~, App\Entity\AdminUser, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Users, label: Admin users, icon: "<i class=\"fa fa-users\"></i>" }

  admin.client_user:
    class: App\Admin\ClientUserAdmin
    arguments: [ ~, App\Entity\ClientUser, ~ ]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Users, label: Clients }

  admin.shop.product_specification:
    class: App\Admin\ShopProductSpecificationAdmin
    arguments: [ ~, App\Entity\ShopProductSpecification, ~ ]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Shop, label: Product specification }

  admin.shop.product_specification_type:
    class: App\Admin\ShopProductSpecificationTypeAdmin
    arguments: [ ~, App\Entity\ShopProductSpecificationType, 'PixSortableBehaviorBundle:SortableAdmin' ]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Shop, label: Product specification type }

  admin.shop.product:
    class: App\Admin\ShopProductAdmin
    arguments: [ ~, App\Entity\ShopProduct, ~ ]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Shop, label: Product }

  admin.shop.order:
    class: App\Admin\OrderAdmin
    arguments: [ ~, App\Entity\Order, App\Controller\Admin\OrderCRUDController ]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Shop, label: Order }

  admin.comment:
    class: App\Admin\CommentAdmin
    arguments: [ ~, App\Entity\Comment, App\Controller\Admin\CommentCRUDController ]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Comments, label: Comments, icon: "<i class=\"fa fa-comment\"></i>" }

  admin.email.email_template:
    class: App\Admin\EmailTemplateAdmin
    arguments: [ ~, App\Entity\EmailTemplate, ~ ]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Email, label: Email template }

  admin.email.email_history:
    class: App\Admin\EmailHistoryAdmin
    arguments: [ ~, App\Entity\EmailHistory, ~ ]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Email, label: Email history }

  admin.payment.pay_pal:
    class: App\Admin\PayPalTransactionAdmin
    arguments: [ ~, App\Entity\PayPalTransaction, ~ ]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Payment, label: PayPal }
