homepage:
  path: /{reactRouting}
  controller: App\Controller\IndexController::index
  defaults:
    reactRouting: .+
  requirements:
    reactRouting: .+
  methods: "GET"

api_login_check:
  path: /api/login_check
